### ISSUE TITLE
Unable to resolve the request: users/session-info

### ISSUE THREAD

**Issue by dgrigg** [clarknelson/craft-recaptcha-3#8]
I'm trying to set this up. The captcha javascript is loading correctly but when the javascript runs to check the user session I'm getting an error

This is the url being called
/index.php?p=admin/actions/users/session-info&dontExtendSession=1

and this is the error returned

{"error":"Unable to resolve the request: users/session-info"}

I tried hitting that url directly and I get the same error 

I'm running Craft 3.3.17

**Comment by clarknelson** [comment]
Can you please update to the latest version of craft? 3.4.x

**Comment by dgrigg** [comment]
that did the trick, thanks

**Comment by dgrigg** [comment]
one thing I'm noticing though, it only works when I'm logged in the admin panel. If I'm signed out i get a 503 service unavailable on this call "http://local.thefabricofourlives.com/actions/craft-recaptcha-3/default". I suspect it's because the controller methods are not flagged for anonymous access.

**Comment by clarknelson** [comment]
yes we changed the endpoint to prevent it from being recognized as a route by the front-end. I will take a look at allowing even if you are signed out?

**Comment by dgrigg** [comment]
That would be great, the problem is I really need Captcha for non signed in users.

**Comment by clarknelson** [comment]
The captcha should work for non-signed in users, take a look at this logic:

```
if(array_key_exists('response', $request)){
   // continue with program
} else {
  $this->requireCpRequest();
}
```

The controller endpoint should require a key from the front-end script calling it. By just visiting the `/actions/craft-recaptcha-3/default` url this key/value will not be included. In this case it will require a CP request which will require the user to log in.

I've changed $this->requireCpRequest(); to $this->asErrorJson('There was no response key attached to the request, we can not continue without this key.');

I believe this will now show a 404 no template error instead of a 503 please sign in.

Thanks, let me know if this works or if you have other questions.

**Comment by dgrigg** [comment]
That looks better, thanks.
